# Generated by Django 5.1 on 2024-08-29 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HookTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="标题")),
                ("content", models.TextField(verbose_name="脚本内容")),
                (
                    "hook_type",
                    models.IntegerField(
                        choices=[
                            (2, "下载前"),
                            (4, "下载后"),
                            (6, "发布前"),
                            (8, "发布后"),
                        ],
                        verbose_name="钩子类型",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="项目名称")),
                ("repo", models.CharField(max_length=256, verbose_name="仓库地址")),
                (
                    "env",
                    models.CharField(
                        choices=[("prod", "生产环境"), ("test", "测试环境")],
                        default="test",
                        max_length=128,
                        verbose_name="环境",
                    ),
                ),
                ("path", models.CharField(max_length=256, verbose_name="线上项目路径")),
            ],
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=128, verbose_name="主机名")),
            ],
        ),
        migrations.CreateModel(
            name="DeployTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=64, verbose_name="标识")),
                ("tag", models.CharField(max_length=128, verbose_name="版本号")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "待发布"),
                            (2, "发布中"),
                            (3, "成功"),
                            (4, "失败"),
                        ],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "before_download_script",
                    models.TextField(blank=True, null=True, verbose_name="下载前脚本"),
                ),
                (
                    "after_download_script",
                    models.TextField(blank=True, null=True, verbose_name="下载后脚本"),
                ),
                (
                    "before_deploy_script",
                    models.TextField(blank=True, null=True, verbose_name="发布前脚本"),
                ),
                (
                    "after_deploy_script",
                    models.TextField(blank=True, null=True, verbose_name="发布后脚本"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.project",
                        verbose_name="项目环境",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="servers",
            field=models.ManyToManyField(to="web.server", verbose_name="关联服务器"),
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=32, verbose_name="节点文字")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lightgray", "待发布"),
                            ("green", "成功"),
                            ("red", "失败"),
                        ],
                        default="lightgray",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.node",
                        verbose_name="父节点",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.deploytask",
                        verbose_name="发布任务单",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.server",
                        verbose_name="服务器",
                    ),
                ),
            ],
        ),
    ]
