# Generated by Django 5.1 on 2024-08-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                ("phone", models.CharField(max_length=32, verbose_name="手机号")),
                ("email", models.CharField(max_length=32, verbose_name="邮箱")),
            ],
        ),
    ]
